### ISSUE TITLE
Cannot get cookies when use getUserCredential function

### ISSUE THREAD

**Issue by sunjunwei11** [Rishikant181/Rettiwt-Auth#13]
When use getUserCredential function, can not get cookies field from the return credential.

`new Auth().getUserCredential({
    email: 'account_email',
    userName: 'account_username',
    password: 'account_password
}).then(credential => {
    ...
})`

**Comment by Rishikant181** [comment]
Have you tried logging in from a browser first using the same account just to check if it's logging in as usual?

Another thing to note: Check if you are being asked for any OTP or Captcha verification while logging in from the browser.

**Comment by Rishikant181** [comment]
btw, [CLI-Usage](https://github.com/Rishikant181/Rettiwt-Auth#cli-usage) is the recommended approach when using it for Rettiwt-API

**Comment by LiteRocks** [comment]
i have the same issue , when i used CLI, I got the following result:AuthHeader {
  authorization: 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA'
}

**Comment by sunjunwei11** [comment]
I try it, [CLI-Usage](https://github.com/Rishikant181/Rettiwt-Auth#cli-usage) also can not get the cookies field.

**Comment by Rishikant181** [comment]
@sunjunwei11 did you try logging in from the browser to check if it's logging in as usual or not?

**Comment by Noflare** [comment]
Hello, I don't have a cookie field

![image](https://github.com/Rishikant181/Rettiwt-Auth/assets/80207554/e43ab949-5b73-433f-af88-69221ce81b67)

![image](https://github.com/Rishikant181/Rettiwt-Auth/assets/80207554/30a1e5b2-8230-4117-b80b-cad3fee61b06)

**Comment by Rishikant181** [comment]
@Noflare did you try logging in from browser?
