### ISSUE TITLE
Improvement - bypass login detection with auth_token

### ISSUE THREAD

**Issue by ItsNash0** [Rishikant181/Rettiwt-Auth#19]
Imagine you have the auth_token before using this library, can you fetch the rest of the cookies and csrf without logging in using the email/password? would be extremely useful to bypass bot detection

**Comment by Rishikant181** [comment]
Simply the auth_token is not enough, since it's common for all users. You need only the cookies. You can do so by using Twitter from the browser and inspecting the outgoing requests' cookie field. You may copy those cookies and use that to authenticate Rettiwt-API.
